### ISSUE TITLE
Keyboard Calibration Issues

### ISSUE THREAD

**Issue by wacaine** [ricrpi/mupen64plus-rpi#20]
If anyone could help I would be eternally grateful.  I compiled on my Pi the ric_dev branch version 2.0.   I launch mupen from the command line.  All the keyboard keys work BUT after pushing the right arrow one time it seems to get stuck.  It is like it does not release.  When I return the command line I see the following output over and over again as if the "onkeyup" listen did not pick up I let go of the right button.  

Core Warning: two events of type 0x8 in interrupt queue
304 key_b pressed 80
304 key_b pressed 80
.......
See full captured output below....................

This kind of output does not happen for the other keys.  Why is it reporting key_b pressed when I press the right arrow on my keyboard?  I may see the output but only while I am press the key.  If I were playing a game this would cause my character to go in right circles or on screen cursor to just to move the right side of the screen and not get off it.  I get the same issue with the right and up directions on my USB game pad.  Is there a calibrate input tool I could use to fix this?

Weirdly enough after I am stuck with the right key I cannot get the left key to work anymore.  The only way I can go left is to now press the right arrow key which now works as my left button... very wierd.    I have not changed any key configurations.  I took what came with the install/compile.  Also same sticky issue occurs for the 'down' button.  I have retropi 1.9.1 also installed and my SNES emulator as well as doom work find with no sticky keys.

Output for the Right key stuck.  Same output for the stuck Down arrow key but instead reports
298 key_a pressed 176
298 key_a pressed 176

---
## START Right key sticky

---

|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ | |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ | '_ | || |_| |_) | | | | / **|  
| |  | | |_| | |_) |  __/ | | | (_) |**   _|  __/| | |_| __ \  
|_|  |_|__,_| .**/ _**|_| |_|_**/   |_| |_|   |_|\**,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.0.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.0.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Mupen64Plus Demo by Marshallh (GPL)
Core: Name: Mupen64Plus  
Core: MD5: DBF04773EC2B8ADF8A94DB7E3E461138
Core: CRC: ddba4de5 b107004a
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 1048576 bytes (or 1 Mb or 8 Megabits)
Core: Version: 1444
Core: Manufacturer: 0
Core: Country: Demo
UI-Console Status: Cheat codes disabled.
Video: DEBUG Video-Rice InitConfiguration() 658
Video: DEBUG Video-Rice set default configuration
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.0.0
UI-Console: using Audio plugin: 'Mupen64Plus RPI Audio Plugin' v2.0.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: DEBUG Video-Rice InitConfiguration() 835
Video: DEBUG Video-Rice set default configuration
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Video: Disabled SSE processing.
Video: Found ROM 'Mupen64Plus', CRC e54dbadd4a0007b1-00
Video: Initializing OpenGL Device Context.
Video: Using OpenGL: Broadcom - VideoCore IV HW : OpenGL ES 2.0
Audio: RPI Audio plugin Initialized. Output Frequency 32000 Hz
Core: Starting R4300 emulator: Dynamic Recompiler
Core: Init new dynarec
Core Warning: two events of type 0x8 in interrupt queue
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
Video: Mupen64Plus OpenGL Video Plugin by Rice v2.0.0 - 36.600 VI/S
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
304 key_b pressed 80
Core Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.

**Comment by ricrpi** [comment]
The keyboard has never worked fully on any branch and only the Esc key works (only one mapped) when running in X windows. 

This is purely a mupen64plus-rpi issue and as you can see by some of the output, is proving difficult to fix. 

This problem also manifests when running remotely (where pressing a key in ssh toggles the input on the system).

For now, please use a joystick / gamepad if you have one.

**Comment by ricrpi** [comment]
See Issue #5
