### ISSUE TITLE
Says deprecated. 

### ISSUE THREAD

**Issue by taybart** [ricrpi/mupen64plus-rpi#28]
If this repo is deprecated where is the new repo? Is nobody working on this?/Would anyone like to? I saw the link to the blog but there is no real mention to a new repo...ricrpi? you there?

**Comment by ricrpi** [comment]
Please use http://github.com/ricrpi/mupen64plus instead. 

I am currently working on a side project (ricrpi/R4300-code-anaysis) that I will eventually integrate into ricrpi/mupen64plus-core. 

If anyone want to help then it is basically a new dynamic recompiler (for ARM only) but hopefully its far more readable than the exisiting one.
