### ISSUE TITLE
gcc: internal compiler error: Terminated (program cc1)

### ISSUE THREAD

**Issue by christianschmidt** [ricrpi/mupen64plus-rpi#4]
Found your work via http://www.raspberrypi.org/phpBB3/viewtopic.php?f=78&t=6761&start=50 and really enjoy the thought of having a playble n64 emulation on the pi in the near future.

tried to build it on my raspi (running retroPie atm), but ran into a problem. at first i thought it ran out of ram (256mb version here), but keeping an eye on the memory via bulding progress with top revealed some ram (incl. swap space) left.

any ideas? could it be still running out of ram? any way to build it anyways?

```
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)
pi@raspberrypi ~/mupen64plus-rpi $ sudo ./m64p_build.sh
************************************ Building core library
[...]
In file included from ../../src/r4300/new_dynarec/new_dynarec.c:961:0:
../../src/r4300/new_dynarec/assem_arm.c: In function ‘loadlr_assemble_arm’:
../../src/r4300/new_dynarec/assem_arm.c:3280:10: warning: ‘memtarget’ may be used uninitialized in this function [-Wuninitialized]
../../src/r4300/new_dynarec/new_dynarec.c: In function ‘storelr_assemble’:
../../src/r4300/new_dynarec/new_dynarec.c:3402:10: warning: ‘memtarget’ may be used uninitialized in this function [-Wuninitialized]
gcc: internal compiler error: Getötet (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make: *** [_obj/r4300/new_dynarec/new_dynarec.o] Fehler 4
make: Leaving directory `/home/pi/mupen64plus-rpi/source/mupen64plus-core/projects/unix'
```

**Comment by arimal** [comment]
Was experiencing the same issue on my 256mb model b, switched my memory split to 64/192(It was 128/128) seems to do the trick and it compiles fine.
