### ISSUE TITLE
Keyboard input - Can't control games

### ISSUE THREAD

**Issue by gyeben** [ricrpi/mupen64plus-rpi#5]
Keyboard input now works under X, eg: I can stop the emulator by pressing 'R', but I can't actually the game. I literally tried all the buttons on my keyboard and I only found buttons for START and Z Trigger (IRC).

**Comment by ricrpi** [comment]
This is probably due to the different mappings between SDL and X windows (if they are different). I have tried setting values for pausing, fullscreen and close rom to X window keys 9 (ESC), 33 (p) 41 (f) and they have successfully worked.

**Comment by gyeben** [comment]
Could you please tell me that where are these settings stored? Thanks!

2013/10/14 ricrpi notifications@github.com

**Comment by ricrpi** [comment]
The values are stored in the mupen64plus.cfg file. 

Keyboard input when in console mode is only implemented in the ric_dev branch and the values are different to X windows and SDL. 

Once I have the key mapping information I'll map them all to SDL values.

**Comment by ricrpi** [comment]
It looks like the keyboard 'keydown / keyup' state may be reversed. Probably broken in mupen64plus-core/src/api/rpigles.c. 

Need to check Xwindow key states passing into input plugin.
