### ISSUE TITLE
Joystick input defined in [core events] does not respond.

### ISSUE THREAD

**Issue by arimal** [ricrpi/mupen64plus-rpi#6]
In mupen64plus.cfg under [core events] options such as "Joy Mapping Stop" "Joy Mapping Pause" and the rest do nothing if set.  I've tested under X and console with no results.  The code in eventloop.c is no different than any other mupen, although my experience with C is limited I see no reason why main_stop() shouldn't be called.  Maybe I'll throw a few print statements just to see if those events are even firing off?

Unless it's just me of course, and I'm doing something dumb.  I've tried to be thorough but it wouldn't be the first time.

**Comment by KingScooty** [comment]
I've not been able to get any input device to work at all so far.

**Comment by ricrpi** [comment]
Is the input device listed when the emulator starts up?

**Comment by ricrpi** [comment]
I'll read the question next time, core events from joystick use an SDL function which does not appear to work on the pi. Therefore this is not a mupen64plus issue and should be corrected in the SDL libraries.

**Comment by arimal** [comment]
Okay then what function are you referring to?  So I can track down whoever is maintaining SDL for the Pi, and maybe report that bug.

**Comment by ricrpi** [comment]
in mupen64plus-core/src/main/eventloop.c 

SDL_SetEventFilter() is used to set-up a callback to the mupen64plus function 'SDLCALL event_sdl_filter(void*,SDL_Event)' so when any event occurs (e.g. joysick button press), the filter is run.

As far as I remember eventloop.c has not been modified and works fine on other platforms so the SDL implementation is not consistent on the pi.

**Comment by ricrpi** [comment]
I suppose SDL_AddEventWatch() could be tried ...

**Comment by ricrpi** [comment]
SDL_AddEventWatch() isn't available on rpi at the moment.
