### ISSUE TITLE
Settings from RiceVideoLinux.ini not being applied.

### ISSUE THREAD

**Issue by arimal** [ricrpi/mupen64plus-rpi#7]
Trying to set ScreenUpdateSetting=# in the .ini file does not seem to take though as far as I can tell the file is being read.  Mupen insists on using whatever is set in mupen64plus.cfg

**Comment by ricrpi** [comment]
@arimal

I cannot reproduce this problem I'm afraid. 

Only advice would be to check the line for the CRC:

Video: Found ROM 'THE LEGEND OF ZELDA', CRC b71170ec2bd71676-45

As there are multiple records for some games. 

I have tried setting ScreenUpdateSetting=6 for Zelda and can see it propagate though into currentRomOptions.screenUpdateSetting and change the behaviour of the screen update.

Could you retest and close if this is ok or provide a more specific test case / screen output?
